# Pandas tutorial
- panda is a open source,BSD-licensed liberary provides a high-performance,esy to use data structure.
- and data analysis tools for the python programming.

Agenda  
- what is Data frame?  >: pandas load the datab
- 
**Answer**-- Data frame combination both column or rows it will basically show you represention format how your data exectly looks like in exelsheet
- in the same way loaded..
- what is Data series?
- different operation in pandas?

In [1]:
# first step is to import pandas 

import pandas as pd
import numpy as np

In [2]:
# playing with DataFrame 
df =pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["coloumn1","coloumn2","coloumn3","coloumn4"])

In [3]:
df.head()

coloumn1  coloumn2  coloumn3  coloumn4
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [4]:
df.to_csv('test1.csv')   ## this give you an excelsheet. on another file

In [5]:
df.to_csv('test2.csv')  

In [6]:
## Accessing the elements
# 1.  .loc >: normal also 
# 2   .iloc >: index locations both row and coloumn

df.loc['Row1']

coloumn1    0
coloumn2    1
coloumn3    2
coloumn4    3
Name: Row1, dtype: int32

In [7]:
df.loc['Row1','coloumn4']

3

In [8]:
df.loc['Row2','coloumn2']

5

In [9]:
df.iloc[:,:]

coloumn1  coloumn2  coloumn3  coloumn4
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [10]:
df.iloc[0:2,0:2]        # for gating three rows 0:3
                # and wants just two coloumn 0:2  

coloumn1  coloumn2
Row1         0         1
Row2         4         5

In [11]:
type(df.iloc[0:2,0:2]) 

pandas.core.frame.DataFrame

In [12]:
type(df.iloc)

pandas.core.indexing._iLocIndexer

In [13]:
## take the elements from the column2
df.iloc[:,1:]

coloumn2  coloumn3  coloumn4
Row1         1         2         3
Row2         5         6         7
Row3         9        10        11
Row4        13        14        15
Row5        17        18        19

In [14]:
#convert Dataframe into array 
df.iloc[:,1:].values  

# this .value will convert dataframe into array


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [15]:
df.iloc[:,:].values.shape

(5, 4)

In [16]:
## **how to check null condition 

df.isnull().sum()

coloumn1    0
coloumn2    0
coloumn3    0
coloumn4    0
dtype: int64

In [17]:
df

coloumn1  coloumn2  coloumn3  coloumn4
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [18]:
df['coloumn1'].value_counts()

coloumn1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [19]:
df['coloumn1'].unique()

array([ 0,  4,  8, 12, 16])

In [20]:
df[['coloumn3','coloumn4']]  #for 1 or 2 or more coloumn need two brackets [[]] 
                             #you have to create a list for multiple coloumn   

coloumn3  coloumn4
Row1         2         3
Row2         6         7
Row3        10        11
Row4        14        15
Row5        18        19

# Reading csv file  

In [21]:
df=pd.read_csv('Test1.csv')   # coma seperated value (CVS)

In [22]:
df=pd.read_csv('Test1.csv')   # coma seperated value (CVS)

In [23]:
df.head()

Unnamed: 0  coloumn1  coloumn2  coloumn3  coloumn4
0       Row1         0         1         2         3
1       Row2         4         5         6         7
2       Row3         8         9        10        11
3       Row4        12        13        14        15
4       Row5        16        17        18        19

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5 non-null      object
 1   coloumn1    5 non-null      int64 
 2   coloumn2    5 non-null      int64 
 3   coloumn3    5 non-null      int64 
 4   coloumn4    5 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes


In [25]:
df.describe()

coloumn1   coloumn2   coloumn3   coloumn4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [26]:
# get the unique catagory counts
df['coloumn1'].unique()

array([ 0,  4,  8, 12, 16], dtype=int64)

In [27]:
# get the uniqe catagory counyts
df['coloumn1'].value_counts()

coloumn1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

# CSV 

In [28]:
# from io import stringIo, Bytes

In [30]:
import pandas as pd
import io as stringIo
import numpy as np

In [31]:
# specifing coloumns data type 
data = ('a,b,c,d\n'
          '1,2,3,4\n'
          '5,6,7\n'
          '8,9,10,11' )

In [32]:
print(data)

a,b,c,d
1,2,3,4
5,6,7
8,9,10,11


In [33]:
df=pd.read_csv(test1(data),dtype=int)

NameError: name 'test1' is not defined

In [34]:
data = ('index,a,b,c\n'
            '4,orange,bat,5.6\n'
            '8,apple,cow,10\n' )

In [35]:
print(data)

index,a,b,c
4,orange,bat,5.6
8,apple,cow,10



In [36]:
pd.read_cvs(stringIo(data))

AttributeError: module 'pandas' has no attribute 'read_cvs'

In [37]:
## URL to CSVs 
s = pd.Series([1,2,3,4,5])


In [42]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [50]:
df = pd.DataFrame(np.arange(0,9).reshape(3,3),index=['Row1','Row2','Row3'],columns=["coloumn1","coloumn2","coloumn3"])

In [51]:
df

coloumn1  coloumn2  coloumn3
Row1         0         1         2
Row2         3         4         5
Row3         6         7         8

In [52]:
df = pd.DataFrame({"names":["prince","jain","oppp"],"marks":[100,59,60]})

In [53]:
df

names  marks
0  prince    100
1    jain     59
2    oppp     60

# Read Json to csv

In [89]:
Data = '{"employee_name": "prince jain", "email": "princejain566@gmail.com", "job_profile": [{"title1":"Team lead","title2":"sr.developer"}]}'
df1=pd.read_json(Data)

C:\Users\Prince\AppData\Local\Temp\ipykernel_19936\4179621270.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1=pd.read_json(Data)


In [83]:
import pandas as pd
import numpy as np

data = {
	"One": {
		"0": 60,
		"1": 60,
		"2": 60,
		"3": 45,
		"4": 45,
		"5": 60
	},
	"Two": {
		"0": 110,
		"1": 117,
		"2": 103,
		"3": 109,
		"4": 117,
		"5": 102
	}
}


In [84]:
data

{'One': {'0': 60, '1': 60, '2': 60, '3': 45, '4': 45, '5': 60},
 'Two': {'0': 110, '1': 117, '2': 103, '3': 109, '4': 117, '5': 102}}

In [85]:
df.head()

names  marks
0  prince    100
1    jain     59
2    oppp     60

In [86]:
# convert json to csv

# .to_csv will make a file 

df.to_csv('wine.csv')

In [87]:
df.to_csv('json file')

In [90]:
df1

employee_name                    email  \
0   prince jain  princejain566@gmail.com   

                                         job_profile  
0  {'title1': 'Team lead', 'title2': 'sr.developer'}

In [94]:
# convert json to different json formats
df.to_json(orient="records")

'[{"names":"prince","marks":100},{"names":"jain","marks":59},{"names":"oppp","marks":60}]'

# Reading HTML content

In [99]:
url ='https://www.geeksforgeeks.org/how-to-read-json-files-with-pandas/'

dfs =pd.read_html(url)

In [109]:
dfs[0]

0
0  import pandas as pd  data = {  "One": {  "0": ...

# Pickling 
- All pandas object are equipped with to_pickle methods which use pythons pickle module to save data structure to disk using
- using a pickle methods..

In [124]:
df_excel.to_pickle('df_excel')

AttributeError: 'tuple' object has no attribute 'to_pickle'